package com.rtpalab5.lab5;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Integer age;
   private java.lang.Double amount;
   private java.lang.Integer division;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public java.lang.Integer getDivision()
   {
      return this.division;
   }

   public void setDivision(java.lang.Integer division)
   {
      this.division = division;
   }

   public Person(java.lang.String name, java.lang.Integer age,
         java.lang.Double amount, java.lang.Integer division)
   {
      this.name = name;
      this.age = age;
      this.amount = amount;
      this.division = division;
   }

}